//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBDUtilityOverlay {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MapImages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MapImages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBDUtilityOverlay.MapImages", typeof(MapImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AUTOHAVEN_WRECKERS_AZAROVS_RESTING_PLACE {
            get {
                object obj = ResourceManager.GetObject("AUTOHAVEN_WRECKERS.AZAROVS_RESTING_PLACE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AUTOHAVEN_WRECKERS_BLOOD_LODGE {
            get {
                object obj = ResourceManager.GetObject("AUTOHAVEN_WRECKERS.BLOOD_LODGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AUTOHAVEN_WRECKERS_GAS_HEAVEN {
            get {
                object obj = ResourceManager.GetObject("AUTOHAVEN_WRECKERS.GAS_HEAVEN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AUTOHAVEN_WRECKERS_WRECKERS_YARD {
            get {
                object obj = ResourceManager.GetObject("AUTOHAVEN_WRECKERS.WRECKERS_YARD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AUTOHAVEN_WRECKERS_WRETCHED_SHOP {
            get {
                object obj = ResourceManager.GetObject("AUTOHAVEN_WRECKERS.WRETCHED_SHOP", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BACKWATER_SWAMP_GRIM_PANTRY {
            get {
                object obj = ResourceManager.GetObject("BACKWATER_SWAMP.GRIM_PANTRY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BACKWATER_SWAMP_THE_PALE_ROSE {
            get {
                object obj = ResourceManager.GetObject("BACKWATER_SWAMP.THE_PALE_ROSE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COLDWIND_FARM_FRACTURED_COWSHED {
            get {
                object obj = ResourceManager.GetObject("COLDWIND_FARM.FRACTURED_COWSHED", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COLDWIND_FARM_RANCID_ABATTOIR {
            get {
                object obj = ResourceManager.GetObject("COLDWIND_FARM.RANCID_ABATTOIR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COLDWIND_FARM_ROTTEN_FIELDS {
            get {
                object obj = ResourceManager.GetObject("COLDWIND_FARM.ROTTEN_FIELDS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COLDWIND_FARM_THE_THOMPSON_HOUSE {
            get {
                object obj = ResourceManager.GetObject("COLDWIND_FARM.THE_THOMPSON_HOUSE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COLDWIND_FARM_TORMENT_CREEK {
            get {
                object obj = ResourceManager.GetObject("COLDWIND_FARM.TORMENT_CREEK", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CROTUS_PRENN_ASYLUM_DISTURBED_WARD {
            get {
                object obj = ResourceManager.GetObject("CROTUS_PRENN_ASYLUM.DISTURBED_WARD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CROTUS_PRENN_ASYLUM_FATHER_CAMPBELLS_CHAPEL {
            get {
                object obj = ResourceManager.GetObject("CROTUS_PRENN_ASYLUM.FATHER_CAMPBELLS_CHAPEL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DVARKA_DEEPWOOD_NOSTROMO_WRECKAGE {
            get {
                object obj = ResourceManager.GetObject("DVARKA_DEEPWOOD.NOSTROMO_WRECKAGE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DVARKA_DEEPWOOD_TOBA_LANDING {
            get {
                object obj = ResourceManager.GetObject("DVARKA_DEEPWOOD.TOBA_LANDING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Empty {
            get {
                object obj = ResourceManager.GetObject("Empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FORSAKEN_BONEYARD_EYRIE_OF_CROWS {
            get {
                object obj = ResourceManager.GetObject("FORSAKEN_BONEYARD.EYRIE_OF_CROWS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GIDEON_MEAT_PLANT_THE_GAME {
            get {
                object obj = ResourceManager.GetObject("GIDEON_MEAT_PLANT.THE_GAME", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GRAVE_OF_GLENVALE_DEAD_DAWG_SALOON {
            get {
                object obj = ResourceManager.GetObject("GRAVE_OF_GLENVALE.DEAD_DAWG_SALOON", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HADDONFIELD_LAMPKIN_LANE {
            get {
                object obj = ResourceManager.GetObject("HADDONFIELD.LAMPKIN_LANE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HAWKINS_NATIONAL_LABORATORY_THE_UNDERGROUND_COMPLEX {
            get {
                object obj = ResourceManager.GetObject("HAWKINS_NATIONAL_LABORATORY.THE_UNDERGROUND_COMPLEX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LÉRYS_MEMORIAL_INSTITUTE_TREATMENT_THEATRE {
            get {
                object obj = ResourceManager.GetObject("LÉRYS_MEMORIAL_INSTITUTE.TREATMENT_THEATRE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotReady {
            get {
                object obj = ResourceManager.GetObject("NotReady", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ORMOND_MOUNT_ORMOND_RESORT {
            get {
                object obj = ResourceManager.GetObject("ORMOND.MOUNT_ORMOND_RESORT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ORMOND_MOUNT_ORMOND_RESORT_2 {
            get {
                object obj = ResourceManager.GetObject("ORMOND.MOUNT_ORMOND_RESORT_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ORMOND_MOUNT_ORMOND_RESORT_3 {
            get {
                object obj = ResourceManager.GetObject("ORMOND.MOUNT_ORMOND_RESORT_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RACCOON_CITY_RACCOON_CITY_POLICE_STATION_EAST_WING {
            get {
                object obj = ResourceManager.GetObject("RACCOON_CITY.RACCOON_CITY_POLICE_STATION_EAST_WING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RACCOON_CITY_RACCOON_CITY_POLICE_STATION_WEST_WING {
            get {
                object obj = ResourceManager.GetObject("RACCOON_CITY.RACCOON_CITY_POLICE_STATION_WEST_WING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RED_FOREST_MOTHERS_DWELLING {
            get {
                object obj = ResourceManager.GetObject("RED_FOREST.MOTHERS_DWELLING", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RED_FOREST_THE_TEMPLE_OF_PURGATION {
            get {
                object obj = ResourceManager.GetObject("RED_FOREST.THE_TEMPLE_OF_PURGATION", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SILENT_HILL_MIDWICH_ELEMENTARY_SCHOOL {
            get {
                object obj = ResourceManager.GetObject("SILENT_HILL.MIDWICH_ELEMENTARY_SCHOOL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPRINGWOOD_BADHAM_PRESCHOOL_I {
            get {
                object obj = ResourceManager.GetObject("SPRINGWOOD.BADHAM_PRESCHOOL_I", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPRINGWOOD_BADHAM_PRESCHOOL_II {
            get {
                object obj = ResourceManager.GetObject("SPRINGWOOD.BADHAM_PRESCHOOL_II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPRINGWOOD_BADHAM_PRESCHOOL_III {
            get {
                object obj = ResourceManager.GetObject("SPRINGWOOD.BADHAM_PRESCHOOL_III", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPRINGWOOD_BADHAM_PRESCHOOL_IV {
            get {
                object obj = ResourceManager.GetObject("SPRINGWOOD.BADHAM_PRESCHOOL_IV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SPRINGWOOD_BADHAM_PRESCHOOL_V {
            get {
                object obj = ResourceManager.GetObject("SPRINGWOOD.BADHAM_PRESCHOOL_V", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap THE_DECIMATED_BORGO_FORGOTTEN_RUINS {
            get {
                object obj = ResourceManager.GetObject("THE_DECIMATED_BORGO.FORGOTTEN_RUINS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap THE_DECIMATED_BORGO_THE_SHATTERED_SQUARE {
            get {
                object obj = ResourceManager.GetObject("THE_DECIMATED_BORGO.THE_SHATTERED_SQUARE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap THE_MACMILLAN_ESTATE_COAL_TOWER {
            get {
                object obj = ResourceManager.GetObject("THE_MACMILLAN_ESTATE.COAL_TOWER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap THE_MACMILLAN_ESTATE_COAL_TOWER_2 {
            get {
                object obj = ResourceManager.GetObject("THE_MACMILLAN_ESTATE.COAL_TOWER_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap THE_MACMILLAN_ESTATE_GROANING_STOREHOUSE {
            get {
                object obj = ResourceManager.GetObject("THE_MACMILLAN_ESTATE.GROANING_STOREHOUSE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap THE_MACMILLAN_ESTATE_GROANING_STOREHOUSE_2 {
            get {
                object obj = ResourceManager.GetObject("THE_MACMILLAN_ESTATE.GROANING_STOREHOUSE_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap THE_MACMILLAN_ESTATE_IRONWORKS_OF_MISERY {
            get {
                object obj = ResourceManager.GetObject("THE_MACMILLAN_ESTATE.IRONWORKS_OF_MISERY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap THE_MACMILLAN_ESTATE_IRONWORKS_OF_MISERY_2 {
            get {
                object obj = ResourceManager.GetObject("THE_MACMILLAN_ESTATE.IRONWORKS_OF_MISERY_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap THE_MACMILLAN_ESTATE_SHELTER_WOODS {
            get {
                object obj = ResourceManager.GetObject("THE_MACMILLAN_ESTATE.SHELTER_WOODS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap THE_MACMILLAN_ESTATE_SHELTER_WOODS_2 {
            get {
                object obj = ResourceManager.GetObject("THE_MACMILLAN_ESTATE.SHELTER_WOODS_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap THE_MACMILLAN_ESTATE_SUFFOCATION_PIT {
            get {
                object obj = ResourceManager.GetObject("THE_MACMILLAN_ESTATE.SUFFOCATION_PIT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap THE_MACMILLAN_ESTATE_SUFFOCATION_PIT_2 {
            get {
                object obj = ResourceManager.GetObject("THE_MACMILLAN_ESTATE.SUFFOCATION_PIT_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WITHERED_ISLE_GARDEN_OF_JOY {
            get {
                object obj = ResourceManager.GetObject("WITHERED_ISLE.GARDEN_OF_JOY", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WITHERED_ISLE_GREENVILLE_SQUARE {
            get {
                object obj = ResourceManager.GetObject("WITHERED_ISLE.GREENVILLE_SQUARE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YAMAOKA_ESTATE_FAMILY_RESIDENCE {
            get {
                object obj = ResourceManager.GetObject("YAMAOKA_ESTATE.FAMILY_RESIDENCE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YAMAOKA_ESTATE_FAMILY_RESIDENCE_2 {
            get {
                object obj = ResourceManager.GetObject("YAMAOKA_ESTATE.FAMILY_RESIDENCE_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YAMAOKA_ESTATE_SANCTUM_OF_WRATH {
            get {
                object obj = ResourceManager.GetObject("YAMAOKA_ESTATE.SANCTUM_OF_WRATH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap YAMAOKA_ESTATE_SANCTUM_OF_WRATH_2 {
            get {
                object obj = ResourceManager.GetObject("YAMAOKA_ESTATE.SANCTUM_OF_WRATH_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
